export const symptomsToSpecialties = {
  "chest pain": "Cardiology",
  "shortness of breath": "Cardiology",
  palpitations: "Cardiology",
  "skin rash": "Dermatology",
  itching: "Dermatology",
  acne: "Dermatology",
  headache: "Neurology",
  dizziness: "Neurology",
  seizures: "Neurology",
  "stomach ache": "Gastroenterology",
  diarrhea: "Gastroenterology",
  constipation: "Gastroenterology",
  "joint pain": "Orthopedics",
  "back pain": "Orthopedics",
  "knee pain": "Orthopedics",
  "high blood pressure": "Cardiology",
  "swollen ankles": "Cardiology",
  fainting: "Cardiology",
  hives: "Dermatology",
  eczema: "Dermatology",
  psoriasis: "Dermatology",
  migraine: "Neurology",
  numbness: "Neurology",
  tremor: "Neurology",
  heartburn: "Gastroenterology",
  bloating: "Gastroenterology",
  vomiting: "Gastroenterology",
  "shoulder pain": "Orthopedics",
  "hip pain": "Orthopedics",
  "wrist pain": "Orthopedics",
  angina: "Cardiology",
  "irregular heartbeat": "Cardiology",
  "chest tightness": "Cardiology",
  "dry skin": "Dermatology",
  sunburn: "Dermatology",
  rosacea: "Dermatology",
  "memory loss": "Neurology",
  weakness: "Neurology",
  "vision problems": "Neurology",
  indigestion: "Gastroenterology",
  ulcers: "Gastroenterology",
  gallstones: "Gastroenterology",
  "elbow pain": "Orthopedics",
  "ankle pain": "Orthopedics",
  "hand pain": "Orthopedics",
  "high cholesterol": "Cardiology",
  "heart murmur": "Cardiology",
  "cold sweats": "Cardiology",
  blisters: "Dermatology",
  warts: "Dermatology",
  scabies: "Dermatology",
  confusion: "Neurology",
  "coordination problems": "Neurology",
  "speech problems": "Neurology",
  "acid reflux": "Gastroenterology",
  hepatitis: "Gastroenterology",
  pancreatitis: "Gastroenterology",
  "muscle pain": "Orthopedics",
  "neck pain": "Orthopedics",
  "foot pain": "Orthopedics",
  "coronary artery disease": "Cardiology",
  "atrial fibrillation": "Cardiology",
  stroke: "Cardiology",
  rashes: "Dermatology",
  dermatitis: "Dermatology",
  melanoma: "Dermatology",
  epilepsy: "Neurology",
  paralysis: "Neurology",
  "sleep disorders": "Neurology",
  "crohn’s disease": "Gastroenterology",
  colitis: "Gastroenterology",
  "irritable bowel syndrome": "Gastroenterology",
  "joint stiffness": "Orthopedics",
  arthritis: "Orthopedics",
  "bone fractures": "Orthopedics",
  "heart attack": "Cardiology",
  "congestive heart failure": "Cardiology",
  "vascular disease": "Cardiology",
  "acne vulgaris": "Dermatology",
  alopecia: "Dermatology",
  "herpes zoster": "Dermatology",
  migraines: "Neurology",
  "multiple sclerosis": "Neurology",
  "parkinson’s disease": "Neurology",
  "hepatitis b": "Gastroenterology",
  "hepatitis c": "Gastroenterology",
  "liver cirrhosis": "Gastroenterology",
  sciatica: "Orthopedics",
  "rotator cuff injury": "Orthopedics",
  "spinal stenosis": "Orthopedics",
  "angina pectoris": "Cardiology",
  "mitral valve prolapse": "Cardiology",
  "peripheral artery disease": "Cardiology",
  "bacterial infections": "Dermatology",
  "fungal infections": "Dermatology",
  vitiligo: "Dermatology",
  "tension headache": "Neurology",
  "cerebral palsy": "Neurology",
  "amyotrophic lateral sclerosis": "Neurology",
  gastritis: "Gastroenterology",
  diverticulitis: "Gastroenterology",
  "celiac disease": "Gastroenterology",
  tendonitis: "Orthopedics",
  "ligament tears": "Orthopedics",
  "meniscus tears": "Orthopedics",
  "ischemic heart disease": "Cardiology",
  "hypertensive heart disease": "Cardiology",
  endocarditis: "Cardiology",
  "allergic reactions": "Dermatology",
  "cold sores": "Dermatology",
  "contact dermatitis": "Dermatology",
  "cluster headache": "Neurology",
  "guillain-barré syndrome": "Neurology",
  "myasthenia gravis": "Neurology",
  "peptic ulcers": "Gastroenterology",
  "esophageal varices": "Gastroenterology",
  "colon polyps": "Gastroenterology",
  "carpal tunnel syndrome": "Orthopedics",
  "plantar fasciitis": "Orthopedics",
  bursitis: "Orthopedics",
  "aortic aneurysm": "Cardiology",
  thrombosis: "Cardiology",
  bradycardia: "Cardiology",
  "eczema herpeticum": "Dermatology",
  "erythema multiforme": "Dermatology",
  "lichen planus": "Dermatology",
  "post-concussion syndrome": "Neurology",
  "huntington’s disease": "Neurology",
  "muscular dystrophy": "Neurology",
  "gastroesophageal reflux disease": "Gastroenterology",
  "lactose intolerance": "Gastroenterology",
  hemorrhoids: "Gastroenterology",
  osteoporosis: "Orthopedics",
  "rheumatoid arthritis": "Orthopedics",
  spondylitis: "Orthopedics",
  hyperlipidemia: "Cardiology",
  tachycardia: "Cardiology",
  cardiomyopathy: "Cardiology",
  melasma: "Dermatology",
  "pityriasis rosea": "Dermatology",
  urticaria: "Dermatology",
  "trigeminal neuralgia": "Neurology",
  "spina bifida": "Neurology",
  "tourette syndrome": "Neurology",
  "helicobacter pylori infection": "Gastroenterology",
  "non-alcoholic fatty liver disease": "Gastroenterology",
  appendicitis: "Gastroenterology",
  gout: "Orthopedics",
  scoliosis: "Orthopedics",
  "chronic pain": "Orthopedics",
  "marfan syndrome": "Cardiology",
  "pulmonary hypertension": "Cardiology",
  myocarditis: "Cardiology",
  dermatomyositis: "Dermatology",
  "hidradenitis suppurativa": "Dermatology",
  porphyria: "Dermatology",
  dementia: "Neurology",
  encephalitis: "Neurology",
  myopathy: "Neurology",
  "clostridium difficile infection": "Gastroenterology",
  "ulcerative colitis": "Gastroenterology",
  "biliary atresia": "Gastroenterology",
  fibromyalgia: "Orthopedics",
  "paget’s disease": "Orthopedics",
  "compartment syndrome": "Orthopedics",
  pericarditis: "Cardiology",
  syncope: "Cardiology",
  "venous insufficiency": "Cardiology",
  "keratosis pilaris": "Dermatology",
  "seborrheic dermatitis": "Dermatology",
  "lichen sclerosus": "Dermatology",
  "peripheral neuropathy": "Neurology",
  meningitis: "Neurology",
  "guillain-barre syndrome": "Neurology",
  "barrett’s esophagus": "Gastroenterology",
  "intestinal obstruction": "Gastroenterology",
  "celiac sprue": "Gastroenterology",
  "achilles tendinitis": "Orthopedics",
  "rotator cuff tear": "Orthopedics",
  "spinal fracture": "Orthopedics",
  "congenital heart defect": "Cardiology",
  "aortic dissection": "Cardiology",
  "rheumatic heart disease": "Cardiology",
  "actinic keratosis": "Dermatology",
  "basal cell carcinoma": "Dermatology",
  "cutaneous lymphoma": "Dermatology",
  "bell’s palsy": "Neurology",
  "cerebral aneurysm": "Neurology",
  "creutzfeldt-jakob disease": "Neurology",
  "colorectal cancer": "Gastroenterology",
  cirrhosis: "Gastroenterology",
  "giardia infection": "Gastroenterology",
  osteoarthritis: "Orthopedics",
  "herniated disc": "Orthopedics",
  "patellar tendinitis": "Orthopedics",
  arrythmia: "Cardiology",
  "cardiac arrest": "Cardiology",
  "mitral stenosis": "Cardiology",
  boils: "Dermatology",
  cellulitis: "Dermatology",
  "cutaneous candidiasis": "Dermatology",
  "cranial nerve disorders": "Neurology",
  hydrocephalus: "Neurology",
  myelitis: "Neurology",
  jaundice: "Gastroenterology",
  hemochromatosis: "Gastroenterology",
  "intestinal perforation": "Gastroenterology",
  "fibrous dysplasia": "Orthopedics",
  "iliotibial band syndrome": "Orthopedics",
  "patellofemoral pain syndrome": "Orthopedics",
};

export const specialties = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Gastroenterology",
  "Orthopedics",
  // Add more specialties
];

export const doctors = [
  {
    id: 1,
    name: "Dr. Smith",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/pTrhfmj2jDA",
    age: 45,
    about: "Dr. Smith has over 20 years of experience in cardiology, specializing in heart health and disease prevention."
  },
  {
    id: 2,
    name: "Dr. Johnson",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/FVh_yqLR9eA",
    age: 38,
    about: "Dr. Johnson is a renowned dermatologist with a focus on skin disorders and cosmetic dermatology."
  },
  {
    id: 3,
    name: "Dr. Lee",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 50,
    about: "Dr. Lee has extensive expertise in neurology, treating a wide range of neurological conditions."
  },
  {
    id: 4,
    name: "Dr. Brown",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/279xIHymPYY",
    age: 47,
    about: "Dr. Brown specializes in digestive health and has a particular interest in endoscopic procedures."
  },
  {
    id: 5,
    name: "Dr. Green",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/rm7rZYdl3rY",
    age: 42,
    about: "Dr. Green focuses on orthopedic surgery, including joint replacements and sports injuries."
  },
  {
    id: 6,
    name: "Dr. Taylor",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/Wyj3IcN6k_s",
    age: 44,
    about: "Dr. Taylor is a skilled cardiologist known for his expertise in interventional cardiology and patient care."
  },
  {
    id: 7,
    name: "Dr. Anderson",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/X7TPR9QYtN0",
    age: 36,
    about: "Dr. Anderson specializes in treating acne, eczema, and other skin conditions, with a passion for patient education."
  },
  {
    id: 8,
    name: "Dr. Thomas",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/UIp163xCV6w",
    age: 55,
    about: "Dr. Thomas is an expert in neurology with a focus on neurodegenerative diseases and patient rehabilitation."
  },
  {
    id: 9,
    name: "Dr. Jackson",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/t9KN97BinLY",
    age: 49,
    about: "Dr. Jackson is known for his work in gastroenterology, particularly in treating inflammatory bowel disease."
  },
  {
    id: 10,
    name: "Dr. White",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/tMFeatBSS4s",
    age: 43,
    about: "Dr. White is a leading orthopedic surgeon with expertise in trauma surgery and rehabilitation."
  },
  {
    id: 11,
    name: "Dr. Harris",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/8xwrBLOATMk",
    age: 46,
    about: "Dr. Harris is a cardiologist dedicated to advancing heart disease treatment and prevention strategies."
  },
  {
    id: 12,
    name: "Dr. Martin",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/DPEPYPBZpB8",
    age: 37,
    about: "Dr. Martin is a board-certified dermatologist with a focus on skin cancer and cosmetic procedures."
  },
  {
    id: 13,
    name: "Dr. Thompson",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/ZCztndOWdjs",
    age: 53,
    about: "Dr. Thompson specializes in neurology, with a particular interest in epilepsy and neurological research."
  },
  {
    id: 14,
    name: "Dr. Garcia",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/grxG4jPkPLs",
    age: 45,
    about: "Dr. Garcia is a gastroenterologist with expertise in liver disease and advanced endoscopic techniques."
  },
  {
    id: 15,
    name: "Dr. Martinez",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/_N7I1JyPYJw",
    age: 39,
    about: "Dr. Martinez focuses on orthopedic surgery, including spine surgery and sports medicine."
  },
  {
    id: 16,
    name: "Dr. Robinson",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/7jjnJ-QA9fY",
    age: 51,
    about: "Dr. Robinson is a cardiologist with expertise in heart disease prevention and rehabilitation."
  },
  {
    id: 17,
    name: "Dr. Clark",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/FLvJ1TUDuaU",
    age: 40,
    about: "Dr. Clark is a dermatologist specializing in eczema, psoriasis, and cosmetic dermatology."
  },
  {
    id: 18,
    name: "Dr. Rodriguez",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/3ewkNkfJj2k",
    age: 45,
    about: "Dr. Rodriguez is a neurologist with a focus on neuroimmunology and multiple sclerosis."
  },
  {
    id: 19,
    name: "Dr. Lewis",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/80NXxDRj6Rg",
    age: 52,
    about: "Dr. Lewis is a gastroenterologist specializing in inflammatory bowel disease and liver disorders."
  },
  {
    id: 20,
    name: "Dr. Walker",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/WjHwape0nfc",
    age: 47,
    about: "Dr. Walker is an orthopedic surgeon focused on knee, shoulder, and sports-related injuries."
  },
  {
    id: 21,
    name: "Dr. Perez",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/qLzWvcQq-V8",
    age: 46,
    about: "Dr. Perez is a cardiologist with a focus on interventional procedures and heart rhythm disorders."
  },
  {
    id: 22,
    name: "Dr. Hall",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/tPxS-1IPZAo",
    age: 39,
    about: "Dr. Hall is a dermatologist specializing in acne, rosacea, and skin cancer detection."
  },
  {
    id: 23,
    name: "Dr. Young",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/_HN4ZNgXH5w",
    age: 49,
    about: "Dr. Young is a neurologist known for his work in epilepsy and neuromuscular disorders."
  },
  {
    id: 24,
    name: "Dr. Allen",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/MMqhO_1xN4I",
    age: 53,
    about: "Dr. Allen is a gastroenterologist focusing on endoscopic procedures and digestive health."
  },
  {
    id: 25,
    name: "Dr. King",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 44,
    about: "Dr. King is an orthopedic surgeon with expertise in joint replacement and trauma surgery."
  },
  {
    id: 26,
    name: "Dr. Wright",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 49,
    about: "Dr. Wright is a cardiologist with a focus on electrophysiology and arrhythmia management."
  },
  {
    id: 27,
    name: "Dr. Scott",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 37,
    about: "Dr. Scott specializes in dermatology, particularly in acne treatment and skin rejuvenation."
  },
  {
    id: 28,
    name: "Dr. Torres",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 50,
    about: "Dr. Torres is an expert in neurology with a focus on epilepsy and headache disorders."
  },
  {
    id: 29,
    name: "Dr. Nguyen",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 46,
    about: "Dr. Nguyen is a gastroenterologist specializing in liver diseases and advanced endoscopic procedures."
  },
  {
    id: 30,
    name: "Dr. Hill",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 44,
    about: "Dr. Hill is an orthopedic surgeon with a focus on sports injuries and joint preservation."
  },
  {
    id: 31,
    name: "Dr. Adams",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 52,
    about: "Dr. Adams is a renowned cardiologist known for his work in interventional cardiology and research."
  },
  {
    id: 32,
    name: "Dr. Baker",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 36,
    about: "Dr. Baker is a dermatologist with expertise in skin cancer, psoriasis, and patient education."
  },
  {
    id: 33,
    name: "Dr. Gonzalez",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 51,
    about: "Dr. Gonzalez specializes in neurology, focusing on neurodegenerative diseases and patient care."
  },
  {
    id: 34,
    name: "Dr. Nelson",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 48,
    about: "Dr. Nelson is a gastroenterologist with expertise in digestive health and minimally invasive procedures."
  },
  {
    id: 35,
    name: "Dr. Carter",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 40,
    about: "Dr. Carter is an orthopedic surgeon specializing in hand and upper extremity surgery."
  },
  {
    id: 36,
    name: "Dr. Mitchell",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 47,
    about: "Dr. Mitchell is a cardiologist with a focus on preventive cardiology and patient wellness."
  },
  {
    id: 37,
    name: "Dr. Perez",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 35,
    about: "Dr. Perez is a dermatologist with a special interest in pediatric dermatology and skin allergy."
  },
  {
    id: 38,
    name: "Dr. Roberts",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 54,
    about: "Dr. Roberts is a neurologist with extensive experience in treating multiple sclerosis and stroke."
  },
  {
    id: 39,
    name: "Dr. Turner",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 49,
    about: "Dr. Turner is a gastroenterologist known for his expertise in endoscopy and inflammatory bowel disease."
  },
  {
    id: 40,
    name: "Dr. Phillips",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 42,
    about: "Dr. Phillips is an orthopedic surgeon with a focus on knee and hip replacement surgeries."
  },
  {
    id: 41,
    name: "Dr. Campbell",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 50,
    about: "Dr. Campbell is a cardiologist dedicated to heart disease prevention and patient-centered care."
  },
  {
    id: 42,
    name: "Dr. Parker",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 38,
    about: "Dr. Parker is a dermatologist with a passion for treating chronic skin conditions and cosmetic procedures."
  },
  {
    id: 43,
    name: "Dr. Evans",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 53,
    about: "Dr. Evans is a neurologist specializing in headache disorders and neuroimaging techniques."
  },
  {
    id: 44,
    name: "Dr. Edwards",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 47,
    about: "Dr. Edwards is a gastroenterologist with a focus on pancreatic diseases and advanced endoscopy."
  },
  {
    id: 45,
    name: "Dr. Collins",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 41,
    about: "Dr. Collins is an orthopedic surgeon specializing in spinal surgery and minimally invasive techniques."
  },
  {
    id: 46,
    name: "Dr. Stewart",
    specialty: "Cardiology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 48,
    about: "Dr. Stewart is a cardiologist with a focus on heart failure and electrophysiology."
  },
  {
    id: 47,
    name: "Dr. Sanchez",
    specialty: "Dermatology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 34,
    about: "Dr. Sanchez is a dermatologist with a special interest in treating acne and skin pigmentation disorders."
  },
  {
    id: 48,
    name: "Dr. Morris",
    specialty: "Neurology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 55,
    about: "Dr. Morris is a neurologist known for his expertise in neurodegenerative diseases and patient care."
  },
  {
    id: 49,
    name: "Dr. Rogers",
    specialty: "Gastroenterology",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 50,
    about: "Dr. Rogers is a gastroenterologist specializing in endoscopic procedures and digestive health."
  },
  {
    id: 50,
    name: "Dr. Reed",
    specialty: "Orthopedics",
    imageUrl: "https://source.unsplash.com/7bMdiIqz_J4",
    age: 44,
    about: "Dr. Reed is an orthopedic surgeon with a focus on sports injuries and joint reconstruction."
  }
];
